# Generated by Django 6.0.3 on 2026-04-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_address_user_phone_user_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='athleteprofile',
            name='height',
            field=models.CharField(blank=True, help_text='e.g., 5\'10" or 178 cm', max_length=20),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='weight',
            field=models.CharField(blank=True, help_text='e.g., 70 kg', max_length=20),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='certification',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
