# Generated by Django 6.0.3 on 2026-04-09 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_alter_dailyroutine_exercises'),
        ('user', '0003_athleteprofile_height_athleteprofile_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachprofile',
            name='sport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coaches', to='player.sport'),
        ),
    ]

