# Generated by Django 6.0.3 on 2026-04-28 13:31

from django.db import migrations, models
 

def set_empty_license_to_null(apps, schema_editor):
    MedicalProfile = apps.get_model('user', 'MedicalProfile')
    MedicalProfile.objects.filter(license_no='').update(license_no=None)


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalprofile',
            name='license_no',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.RunPython(set_empty_license_to_null, migrations.RunPython.noop),
    ]
