# Generated by Django 6.0.3 on 2026-04-07 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_initial_sports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyroutine',
            name='exercises',
            field=models.TextField(blank=True, help_text='List of exercises for this session'),
        ),
    ]
