# Generated by Django 6.0.3 on 2026-04-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_staff', '0002_alter_athletehealthrecord_medical_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='athletehealthrecord',
            name='review_requested',
            field=models.BooleanField(default=False, help_text='Player requested medical review'),
        ),
    ]
